version: '3.8'

networks:
  jenkins-network:
    name: jenkins

volumes:
  data:
    name: jenkins-data

services:

  jenkins:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: jenkins
    restart: unless-stopped
    user: root
    networks:
      - jenkins-network
    ports:
      - 8080:8080
      - 5000:5000
    volumes:
      - data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock